name: 低端机 zyc clang18

on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: 检出仓库
        uses: actions/checkout@v5

      - name: 环境变量配置
        run: |
          cat config.env | grep KERNEL_SOURCE= >> $GITHUB_ENV
          cat config.env | grep KERNEL_SOURCE_BRANCH= >> $GITHUB_ENV
          cat config.env | grep KERNEL_CONFIG= >> $GITHUB_ENV
          cat config.env | grep KERNEL_ZIP_NAME= >> $GITHUB_ENV
          cat config.env | grep KERNEL_IMAGE_NAME= >> $GITHUB_ENV
          cat config.env | grep LLVM_CONFIG= >> $GITHUB_ENV
          cat config.env | grep ENABLE_KERNELSU= >> $GITHUB_ENV
          cat config.env | grep KERNELSU_TAG= >> $GITHUB_ENV
          cat config.env | grep ENABLE_KVM= >> $GITHUB_ENV
          cat config.env | grep ENABLE_LXC_DOCKER= >> $GITHUB_ENV
          cat config.env | grep SWITCH_PYTHON= >> $GITHUB_ENV
          cat config.env | grep NEED_DTBO= >> $GITHUB_ENV

      - name: 显示当前配置
        run: |
          echo "KERNEL_SOURCE=${{ env.KERNEL_SOURCE }}"
          echo "KERNEL_SOURCE_BRANCH=${{ env.KERNEL_SOURCE_BRANCH }}"
          echo "KERNEL_CONFIG=${{ env.KERNEL_CONFIG }}"
          echo "KERNEL_ZIP_NAME=${{ env.KERNEL_ZIP_NAME }}"
          echo "KERNEL_IMAGE_NAME=${{ env.KERNEL_IMAGE_NAME }}"
          echo "LLVM_CONFIG=${{ env.LLVM_CONFIG }}"
          echo "ENABLE_KERNELSU=${{ env.ENABLE_KERNELSU }}"
          echo "KERNELSU_TAG=${{ env.KERNELSU_TAG }}"
          echo "ENABLE_KVM=${{ env.ENABLE_KVM }}"
          echo "ENABLE_LXC_DOCKER=${{ env.ENABLE_LXC_DOCKER }}"
          echo "SWITCH_PYTHON=${{ env.SWITCH_PYTHON }}"
          echo "NEED_DTBO=${{ env.NEED_DTBO }}"

      - name: 构建编译内核环境
        run: |
          sudo apt-get update
          sudo -E apt-get -y -qq install \
            git \
            make \
            bc \
            bison \
            ccache \
            openssl \
            zip \
            kmod \
            cpio \
            flex \
            libelf-dev \
            curl \
            libssl-dev \
            libtfm-dev \
            wget \
            device-tree-compiler \
            ca-certificates \
            python3 \
            python-is-python3 \
            binutils \
            binutils-aarch64-linux-gnu \
            binutils-arm-linux-gnueabi
          mkdir -p $GITHUB_WORKSPACE/kernel_workspace

      - name: 下载 zyc-clang 编译器
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          mkdir -p clang-zyc
          wget https://github.com/ZyCromerZ/Clang/releases/download/18.0.0-20230913-release/Clang-18.0.0-20230913.tar.gz
          tar -C clang-zyc/ -zxf Clang-18.0.0-20230913.tar.gz

      - name: 下载内核源码
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          echo "当前内核源码地址：${{ env.KERNEL_SOURCE }}"
          echo "当前内核源码分支：${{ env.KERNEL_SOURCE_BRANCH }}"
          echo "远程分支列表："
          git ls-remote --heads "${{ env.KERNEL_SOURCE }}"
          git clone "${{ env.KERNEL_SOURCE }}" -b "${{ env.KERNEL_SOURCE_BRANCH }}" android-kernel --depth=1

      - name: 开启 lxc 和 docker 配置
        if: env.ENABLE_LXC_DOCKER == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          wget https://github.com/fate-think/LXC-DOCKER-KernelSU_Action/releases/download/1.0.0/add-lxc-docker-custom.sh
          chmod 755 add-lxc-docker-custom.sh
          ./add-lxc-docker-custom.sh android-kernel/arch/arm64/configs/${{ env.KERNEL_CONFIG }}
          echo "# CONFIG_ANDROID_PARANOID_NETWORK is not set" >> android-kernel/arch/arm64/configs/${{ env.KERNEL_CONFIG }}

      - name: 添加 runc 补丁
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          wget https://github.com/fate-think/LXC-DOCKER-KernelSU_Action/releases/download/1.0.0/runcpatch.sh
          chmod a+x runcpatch.sh

          if [ -f android-kernel/kernel/cgroup.c ]; then
            ./runcpatch.sh android-kernel/kernel/cgroup.c
          fi

          if [ -f android-kernel/kernel/cgroup/cgroup.c ]; then
            ./runcpatch.sh android-kernel/kernel/cgroup/cgroup.c
          fi

      - name: 修复 clang18 部分
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          sed -i "s/CONFIG_CC_STACKPROTECTOR_STRONG=y/# CONFIG_CC_STACKPROTECTOR_STRONG is not set/g" arch/arm64/configs/${{ env.KERNEL_CONFIG }}
          wget https://github.com/fate-think/LXC-DOCKER-KernelSU_Action/releases/download/1.0.0/clangfix2.sh
          chmod u+x clangfix2.sh
          ./clangfix2.sh

      - name: 配置 KernelSU
        if: env.ENABLE_KERNELSU == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s ${{ env.KERNELSU_TAG }}

      - name: 开启 kvm
        if: env.ENABLE_KVM == 'true'
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          echo "CONFIG_VIRTUALIZATION=y" >> android-kernel/arch/arm64/configs/${{ env.KERNEL_CONFIG }}
          echo "CONFIG_KVM=y" >> android-kernel/arch/arm64/configs/${{ env.KERNEL_CONFIG }}
          echo "CONFIG_VHOST_NET=y" >> android-kernel/arch/arm64/configs/${{ env.KERNEL_CONFIG }}
          echo "CONFIG_VHOST_CROSS_ENDIAN_LEGACY=y" >> android-kernel/arch/arm64/configs/${{ env.KERNEL_CONFIG }}

      - name: 设置 ccache 缓存
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: build-kernel-sagit-msm8998
          max-size: 2G

      - name: 开始编译内核
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel

          export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-zyc/bin:$PATH
          export KBUILD_BUILD_HOST=17
          export KBUILD_BUILD_USER=HyperPower

          make -s -j$(nproc --all) O=out ARCH=arm64 ${{ env.KERNEL_CONFIG }}

          if [ "${{ env.LLVM_CONFIG }}" = "y" ]; then
            make -j$(nproc --all) \
              CC="ccache clang" \
              CXX=clang++ \
              O=out \
              ARCH=arm64 \
              CLANG_TRIPLE="aarch64-linux-gnu-" \
              CROSS_COMPILE="aarch64-linux-gnu-" \
              CROSS_COMPILE_ARM32="arm-linux-gnueabi-" \
              LLVM=1 \
              LLVM_IAS=1
          else
            make -j$(nproc --all) \
              CC="ccache clang" \
              CXX=clang++ \
              O=out \
              ARCH=arm64 \
              CLANG_TRIPLE="aarch64-linux-gnu-" \
              CROSS_COMPILE="aarch64-linux-gnu-" \
              CROSS_COMPILE_ARM32="arm-linux-gnueabi-"
          fi

      - name: 准备打包内核
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace

          git clone https://github.com/osm0sis/AnyKernel3

          sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
          sed -i 's!block=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!block=/dev/block/bootdevice/by-name/boot;!g' AnyKernel3/anykernel.sh
          sed -i 's/is_slot_device=1;/is_slot_device=0;/g' AnyKernel3/anykernel.sh

          if [ -f android-kernel/out/arch/arm64/boot/${{ env.KERNEL_IMAGE_NAME }} ]; then
            cp android-kernel/out/arch/arm64/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
          else
            echo "找不到内核镜像文件：android-kernel/out/arch/arm64/boot/${{ env.KERNEL_IMAGE_NAME }}"
            echo "当前 boot 输出目录内容如下："
            ls -lah android-kernel/out/arch/arm64/boot/
            exit 1
          fi

          rm -rf AnyKernel3/.git*
          rm -rf AnyKernel3/README.md
          rm -rf AnyKernel3/ramdisk
          rm -rf AnyKernel3/modules
          rm -rf AnyKernel3/patch

      - name: 打包并上传
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.KERNEL_ZIP_NAME }}
          path: kernel_workspace/AnyKernel3/*
